#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=10
STOP=15

CLOUDFLARED_BIN="/usr/bin/cloudflared"

start() {
        echo start
        # commands to launch application
}

stop() {
        echo stop
        # commands to kill application
}